# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    env:
        TEST_PORT: ${{ secrets.TEST_PORT }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        TEST_DB: ${{ secrets.TEST_DB }}
        SENDER_EMAIL_PASSWORD: ${{ secrets.SENDER_EMAIL_PASSWORD }}
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        REMOTE_DB: ${{ secrets.REMOTE_DB }}
        PORT: ${{ secrets.PORT }}
        OWN_EMAIL: ${{ secrets.OWN_EMAIL }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        DEV_DB: ${{ secrets.DEV_DB }}
        CLOUD_NAME: ${{ secrets.CLOUD_NAME }}
        CLOUD_NAMECLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
